[package]
name = "hello-world"
description = "Using a simple Qobs library from a Git remote to print a hello world."
authors = ["zeozeozeo"]

[target]
sources = ["src/**.cpp", "src/**.cc", "src/**.c"]

[dependencies]
libhelloworld = "gh:zeozeozeo/libhelloworld" # shortcut for github; there are multiple other shortcuts supported
